server:
  port: ${PORT}

spring:
  application:
    name: cafe
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    generate-ddl: false
    database: mysql
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none

logging:
  slack:
    webhook-url: ${SLACK_WEBHOOK_URL}
  config: classpath:logback.xml

jwt:
  secret: ${JWT_SECRET_KEY}

management:
  endpoints:
    web:
      exposure:
        include: health
